version: "3"

services:
  app:
    build:
      context: .
    command: make db run-debug
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - ALLOWED_CORS_ORIGINS=http://localhost:3000
      - MIX_ENV=dev
      - HTTP_PORT=3000
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - DATABASE_NAME=blog_dev
      - DATABASE_POOL_SIZE=5
 
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=blog_dev

  