version: 2
jobs:
  build:
    docker:
      - image: elixir:1.9.1-alpine
        name: app
        environment:
          - MIX_ENV=test
          - HTTP_PORT=3000
          - DATABASE_USER=user
          - DATABASE_PASSWORD=pass
          - DATABASE_PORT=5432
          - DATABASE_HOST=db
          - DATABASE_NAME=blog_test
          - DATABASE_POOL_SIZE=5
      - image: postgres:9.6-alpine
        name: db
        environment:
          - POSTGRES_USER=user  
          - POSTGRES_PASSWORD=pass
          - POSTGRES_DB=blog_test

    working_directory: ~/repo
    steps:
      - checkout
      - run: apk add --update postgresql-client make tzdata git
      - run: cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && echo "America/Sao_Paulo" > /etc/timezone
      - run : mix do local.hex --force, local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test


